import os
import shutil
import threading
from concurrent.futures import ThreadPoolExecutor

import vpk
from core import base, config, constants, fs, log, output, utils


def extract(
    vpk_to_extract_from: vpk.VPK,
    paths: str | list[str],
    path_to_extract_to: str = base.build_dir,
    force: bool = False,
) -> None:
    if isinstance(paths, str):
        paths = [paths]

    paths = list(dict.fromkeys(paths))

    vpk_lock = threading.Lock()

    def extract_file(path: str) -> None:
        full_path = os.path.join(path_to_extract_to, path)
        with vpk_lock:
            # extract files from VPK only once (unless forcing re-extraction after a game update)
            if not force and os.path.exists(full_path):
                return
            output.add_detail("&extracting_terminal", path)
            pakfile = vpk_to_extract_from.get_file(path)

        if pakfile:
            fs.create_dirs(os.path.dirname(full_path))
            with pakfile:
                pakfile.save(full_path)
        else:
            log.write_warning(f"File not found in VPK: {path}")

    with ThreadPoolExecutor() as executor:
        list(executor.map(extract_file, paths))


def dump(vpk_obj: vpk.VPK, output_dir: str, check_exists: bool = True) -> None:
    for filepath in vpk_obj:
        # Sanitize filepath to prevent invalid characters or quotes
        clean_path = filepath.strip().strip('"').strip("'").replace("\\", "/").lstrip("/")
        full_path = os.path.join(output_dir, clean_path)
        if check_exists and os.path.exists(full_path):
            continue

        fs.create_dirs(os.path.dirname(full_path))
        with vpk_obj.get_file(filepath) as pakfile:
            pakfile.save(full_path)


def is_minify_pak(vpk_path: str) -> bool:
    """
    Determines whether a VPK file was generated by Minify. Only minify_version.txt is
    written unconditionally (opt_out_vpk_metadata skips the rest), so it is the sole marker.
    """
    try:
        pak = vpk.open(vpk_path)
        pak_files = set(pak)
    except Exception:
        return False
    return "minify_version.txt" in pak_files


def dump_metadata(
    target_dir: str,
    mod_name: str | None = None,
    vpk_mods: list[str] | None = None,
    extra_lists: dict[str, list[str]] | None = None,
) -> None:
    """
    Standardizes metadata files for generated Paks.
    - target_dir: Where to dump.
    - mod_name: If provided, creates {mod_name}.txt (for single mod patches).
    - vpk_mods: List of VPK mod names for minify_vpk_mods.txt.
    - extra_lists: Dict of {filename: [lines]} for additional metadata files.
    """
    # Always write version marker (regardless of opt_out_vpk_metadata)
    with utils.open_utf8(os.path.join(target_dir, "minify_version.txt"), "w") as f:
        f.write(base.VERSION)

    if config.get("opt_out_vpk_metadata", False):
        return

    # 1. Base Info
    if mod_name is None:
        shutil.copy(base.mods_config_dir, os.path.join(target_dir, "minify_mods.json"))
    else:
        open(os.path.join(target_dir, f"{mod_name}.txt"), "w", encoding="utf-8").close()

    # 2. Lists
    if vpk_mods:
        with utils.open_utf8(os.path.join(target_dir, "minify_vpk_mods.txt"), "w") as f:
            f.write("\n".join(vpk_mods))

    if extra_lists:
        for filename, lines in extra_lists.items():
            with utils.open_utf8(os.path.join(target_dir, filename), "w") as f:
                f.write("\n".join(lines))

    # 3. Dota Version (steam.inf)
    if os.path.exists(constants.dota_steam_inf_path):
        shutil.copy(constants.dota_steam_inf_path, os.path.join(target_dir, "steam.inf"))
